version: "0.1"
name: stub

services:
  api:
    container_name: stub
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - stub-network
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: on-failure

  redis:
    container_name: redis
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - stub-network
    volumes:
      - cache:/data

networks:
  stub-network:
    name: stub-network

volumes:
  cache:
    driver: local
